### ISSUE TITLE
[Code UW]: Convert the NoisePy tutorial to a python notebook

### ISSUE THREAD

**Issue by carlosgjs** [uw-ssec/codeuw#2]
### Contact

carlosg@uw.edu

### Description

The existing tutorial currently in the README.md can be replaced with a Jupyter notebook. 

1. Download [this colab notebook](https://colab.research.google.com/drive/1ir-p05dW34cj4biEZYqa7QXgXpjqv3fW?usp=sharing) and add it to the noisepy repo as `/tutorial.ipynb`.
2. Remove the tutorial steps that are already covered by the notebook from the README.md
3. Verify that the `tutorial.ipynb` can be open and run in [colab](https://colab.research.google.com/) directly from Github.

<img width="779" alt="image" src="https://user-images.githubusercontent.com/10456546/230232356-b43389cc-22b3-422f-a2d9-d5944df00d40.png">

 

### Code Repository

https://github.com/mdenolle/NoisePy

### Version

L2

### What is the primary programming language for the task

python

**Comment by nrich20** [comment]
Tutorial has been converted to a notebook and all steps have been removed from the README. There is still an issue with the notebook being unable to run the graphing function for Step 2: Stacking. We presume it is either because there is not enough data to produce a graph for stacking or the graphing function never worked in the first place.
